# Generated by Django 4.0.3 on 2022-05-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('category',), 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
