# Generated by Django 4.0.3 on 2022-05-03 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='aviable',
            new_name='available',
        ),
    ]
